spring:
  application:
    name: yesaladin-coupon

  datasource:
    url: jdbc:h2:mem:/test
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true

coupon:
  issue:
    unlimited-coupon-issue-size: 100
    unlimited-flag-value: -1
  storage:
    url: https://api-storage.cloud.toast.com/v1/AUTH_fcb81f74e379456b8ca0e091d351a7af
    account: AUTH_fcb81f74e379456b8ca0e091d351a7af
    container-name: yesaladinTest/coupon/test
  storage-token:
    auth:
      url: https://api-identity.infrastructure.cloud.toast.com/v2.0/tokens
      tenant-id: fcb81f74e379456b8ca0e091d351a7af
      username: mmmmm_s2@naver.com
      password: yesaladin